stages:
- name: Build Environment
  steps:
  - publishImageConfig:
      dockerfilePath: Docker/Dockerfile.ubuntu.hirsute
      buildContext: .
      tag: slicer-ubuntu-hirstue
timeout: 60
notification: {}
