FROM ubuntu:hirsute

RUN sudo apt update && sudo apt install git subversion build-essential cmake cmake-curses-gui cmake-qt-gui \
qt5-default qtmultimedia5-dev qttools5-dev libqt5xmlpatterns5-dev libqt5svg5-dev qtwebengine5-dev qtscript5-dev \
qtbase5-private-dev libqt5x11extras5-dev libxt-dev
